### ISSUE TITLE
mfa train 결과 이슈 질문

### ISSUE THREAD

**Issue by Moon-sung-woo** [JH-lee95/Fastspeech2-Korean#1]
안녕하세요. 올려주신 코드 덕분에 많이 참고하여 개발하고 있습니다. 감사합니다.
제가 한국어 데이터를 가지고 duration을 얻기위해 mfa 학습을 진행하였는데 마지막 단어에 대한 duration을 얻지 못해 질문 남깁니다.

제가 mfa를 train 하기 위해 수행한 것은 다음과 같습니다.

1. wav-lab pari 생성 (.wav file과 .lab file이 같은 경로상에 위치)
2. lexicon file 생성 (g2pk를 이용해 phoneme생성)
3. mfa 학습 시작 (mfa train <데이터셋 위치> <lexicon file의 위치> )
- mfa version = 2.0.0rc5

mfa train을 마치고 얻은 TextGrid를 보면 마지막에 대한 문장이 나와있지 않습니다.
혹시 mfa를 이용하셨을 때 저와 같은 현상을 겪으신적이 있는지 궁금하여 이슈 남깁니다.

제가 얻은 TextGrid와 lexicon sample file 및 lexicon file 생성 코드 첨부합니다.
https://drive.google.com/drive/folders/1q-zvEzb4hTOeQKuVwhjkjP2d1rfw-Tl0?usp=sharing
한번 봐주시면 정말 감사하겠습니다.

감사합니다.

**Comment by lsh950919** [comment]
안녕하세요,

사용하신 음성 파일이 없어 추측을 할 수밖에 없지만, 첨부해주신 textgrid 파일에서 words의 시간과 phoneme들의 시간이 차이가 크게 나는 것으로 보아 phoneme에 대한 alignment가 제대로 이뤄지지 않는것으로 보입니다.

저희가 프로젝트를 진행할 당시 KSS dataset을 사용하여 pretrained model 생성 후 이 모델을 사용하여 alignment를 진행했다 보니, 그 과정을 거쳐야 제대로 된 alignment가 나올 것으로 생각됩니다.

[Montreal Forced Aligner](https://montreal-forced-aligner.readthedocs.io/en/latest/) 모델도 훈련이 필요하다 보니 저희도 기존 한국어 pretrained 모델을 사용하려 했으나 문제가 생겨 [KSS dataset](https://www.kaggle.com/datasets/bryanpark/korean-single-speaker-speech-dataset)을 직접 사용하여 훈련 한 뒤 그 모델을 zip파일로 불러와 사용했던 것으로 기억이 납니다.

또한, 작년에 비해 MFA도 변경점이 꽤 있어보이던데 이들이 제공하는 한국어 pretrained 모델을 불러와서 사용해보고 성능이 어떤지 확인해보는것도 방법이 될 것 같습니다.

충분한 답변이 됐으면 좋겠네요.

**Comment by Moon-sung-woo** [comment]
안녕하세요 @lsh950919 님. 답변 정말 감사합니다.
mfa train 방법에 대한 질문이 있어 추가로 질문 남기게 되었습니다.
mfa를 처음 해보다 보니 부족한게 많습니다 ㅠㅠ

Q1. 제가 수행한 방법(mfa train <데이터셋 위치> <lexicon file의 위치>)이 pretrained model을 생성한 후 alignment를 함께 수행하는게 아닌가요??
Q2. 만약 mfa train만 하면 되는게 아닌 다른것도 해줘야 한다면 어떤 과정을 거치셨는지 공유해주실 수 있다면 도움을 받고 싶습니다.

위의 구글 드라이브에 음성 파일을 추가했습니다.
확인 해주시면 정말 감사드리겠습니다.

감사합니다.

**Comment by lsh950919** [comment]
안녕하세요,

답변을 드리자면

Q1. 지금 사용하신 방식은 아무것도 훈련시키지 않은 MFA 모델을 2개의 음성파일만 넣어 훈련 시킨 것으로 확인 되는데, 이렇게 되면 모델이 훈련을 많이 거치지 않아 성능이 제대로 나오지 않습니다. 좋은 alignment를 내기 위해서는 최대한 많은 audio/annotation pair를 넣어 훈련을 시킨 뒤에 이 훈련 시킨 모델을 원하는 음성파일에 적용을 시켜줘야 합니다. 딥러닝에서 train을 통해 pretrained 모델을 만든 뒤에 해당 pretrained 모델로 inference를 한다고 생각하시면 됩니다.

Q2. 저도 작년에 프로젝트가 끝난 이후 follow up을 하는 중이 아니다 보니 지금은 바뀌었을수도 있지만, 과정 자체는 말씀 드렸던 대로
1. KSS dataset 준비, kss lexicon g2pk로 추출
2. `mfa train <kss 위치> <kss lexicon 위치>` -> zip 파일 생성되는 argument script에 추가 필요
3. 위에서 나온 zip파일로 `mfa align` script 진행
위 과정을 통해 추출을 했습니다.

그 때 사용했던 코드 자체는 공유하기가 힘들어 어떤 코드를 써야 하는지는 [MFA](https://montreal-forced-aligner.readthedocs.io/en/latest/first_steps/example.html)를 참고하시는게 좋을 것 같습니다. MFA documentation이 작년에 비해 많이 추가가 돼서 examples 부분 참고 하시면 도움이 될겁니다.

또한 해당 [블로그](https://chldkato.tistory.com/195)에서도 비슷한 방법으로 진행 했는데, 이 포스트는 g2pk가 아닌 g2p를 사용한 점 참고하시기 바랍니다.

**Comment by Moon-sung-woo** [comment]
안녕하세요 @lsh950919 님 답변 감사합니다.
먼저 MFA 모델을 11240개의 한국어 오디오 dataset을 가지고 `mfa train <데이터셋 위치> <lexicon file의 위치> <TextGrid 저장 폴더>`를 이용해 바로 TextGrid를 얻었습니다.
공유해주신 MFA 사이트 들어가 `use case 3번`으로 진행했습니다 ㅠㅠ

Q1. use case 3번으로 진행한 것이 @lsh950919 님이 Q2에 대한 답변으로 주신것과 다른것일까요? 어떤 차이인지를 모르겠습니다.
Q2. 데이터가 부족해서일까요? KSS dataset을 추가 하여 더 학습을 진행해야 될지 모르겠습니다 ㅠㅠ

바쁘신 시간 내서 답변 달아주셔서 정말 감사드립니다.
감사합니다.

**Comment by lsh950919** [comment]
안녕하세요,

use case 3번이 어떤건지는 잘 모르겠지만, 훈련할 때 사용한 데이터셋이 alignment를 적용해야 하는 데이터라면 그 데이터로 훈련을 하는것이 아니라 kss dataset으로 훈련한 뒤 align을 하는게 필요해보입니다.

사용하신 11240개의 음성이 실제로 적용하려는 데이터가 아닌 훈련용 데이터라면 데이터의 음성/단어들이 bias가 있지는 않은지 등의 여부를 확인해보셔야 phoneme alignment가 뒤로 밀리는 이유를 알 수 있을거 같네요.

**Comment by Moon-sung-woo** [comment]
안녕하세요 @lsh950919 님.
답변 정말 감사합니다.
말씀해주신 내용을 토대로 실험을 더 진행해 보도록 하겠습니다.
이슈는 닫도록 하겠습니다.
정말 많은 도움 되었습니다. 감사합니다.
